{% set name = "hipcc" %}
{% set version = "6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/HIPCC/archive/refs/tags/rocm-6.0.2.tar.gz
  sha256: d6209b14fccdd00d7231dec4b4f962aa23914b9dde389ba961370e8ba918bde5
  patches:
    - 0001-Remove-QUIET-from-cmake-rocm-detection.patch
    - 0001-Make-rocm-cmake-required.patch

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - rocm-cmake  {{ version }}
  run:
    - rocminfo {{ version }}
    - clang
    - clangxx
    - perl

test:
  commands:
    - test -f $PREFIX/bin/hipcc
    #- ${PREFIX}/bin/hipcc --help
    - hipconfig
    - hipconfig.bin

about:
  home: https://github.com/ROCm/HIPCC
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'HIPCC: HIP compiler driver'

extra:
  recipe-maintainers:
    - isuruf
